inherit_from: .rubocop_todo.yml

# 自動生成されるものはチェック対象から除外する
AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - 'db/**/*'
    - 'Capfile'
    - 'config/deploy.rb'
    - config/initializers/geokit_config.rb
  SuggestExtensions: false
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

# private/protected は一段深くインデントする
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

# ブロックの行数チェック
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/environments/*'

Metrics/AbcSize:
  Max: 40

# 日本語コメントチェックを無効
Style/AsciiComments:
  Enabled: false