version: 2
jobs:
  build:
    docker:
      image: cimg/base:2022.09
    working_directory: ~/JunkissaTrip
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Install Docker Compose
      #     environment:
      #       COMPOSE_VERSION: '1.29.2'
      #     command: |
      #       curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
      #       chmod +x ~/docker-compose
      #       sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker network create
          command: |
            set -x
            docker network create jt-network
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose -f docker-compose-dev.yml up -d --build 
      - run:
          name: wait for DB setup
          command: |
            sleep 10
      - run:
          name: DB migration
          command: docker-compose -f docker-compose-dev.yml run app rails db:migrate RAILS_ENV=test
      - run:
          name: test
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            docker-compose -f docker-compose-dev.yml run app bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - run:
          name: docker-compose down
          command: docker-compose -f docker-compose-dev.yml down